### ISSUE TITLE
Link build badge to Travis

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-offcanvas#1]
Bulld badge leads to just image :(

**Comment by GeorgMeyer23** [comment]
LOL, not yet ready and already an open issue. 
Fixed in e7683d780c7a577998751cce1debbe0929c6cf0a

**Comment by ain** [comment]
@GeorgMeyer23 I was checking the build result from Travis yesterday when we discussed it and failed to get it, instant bug!
